---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sasrvapiregister
  namespace: qa-interop-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::183295434367:role/qa-interoperabilidad-us-east-1-sasrvapiregister
